### ISSUE TITLE
Button width

### ISSUE THREAD

**Issue by alexbofa** [alemelis/sd-webui-ar#11]
Hello

I want to suggest adding `style.css` to the folder `..\extensions\sd-webui-ar` to expand the buttons for more informative.
Extend the distance from the buttons. So it's perfect to fit **640x640, 640x840** and etc.

![after-before](https://user-images.githubusercontent.com/58225118/228280824-b9c04a04-c658-4bbe-adbd-535469be2543.png)

I don't understand **css** well, but I did it for myself. Maybe it will be useful for future updates.

**Example:**
```
#txt2img_row_aspect_ratio button,
#img2img_row_aspect_ratio button {
	margin: 0.25em 0 0.625em 0 !important;
	padding: 0 1.3em 0 1.3em !important;
}

#txt2img_row_resolutions button,
#img2img_row_resolutions button {
	min-width: 4.5em !important;
	max-width: fit-content !important;
	margin: 0 0 0.25em 0 !important;
}
```

**Comment by alemelis** [comment]
hi @alexbofa 

thanks! I was wondering how to do it, but I know less CSS thank you 😛 

are you happy for me to steal this?
otherwise feel free to open a PR
