### ISSUE TITLE
How to promote stable diffusion extensions?

### ISSUE THREAD

**Issue by todhm** [alemelis/sd-webui-ar#14]
Dear alemelis

I recently developed a community extension repository that helps users to share their images with others. (https://github.com/learners-superpumped/newtype_v3)
I want to get some users's feedback but I could not find any online community or site that can promote this extension.
Is there any way that we can promote this github?

**Comment by alemelis** [comment]
you can try on reddit
- [https://www.reddit.com/r/StableDiffusion](https://www.reddit.com/r/StableDiffusion)
- [https://www.reddit.com/r/sdforall](https://www.reddit.com/r/sdforall)

or post on AUTOMATIC1111/stable-diffusion-webui [page](https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions)
