### ISSUE TITLE
Big buttons

### ISSUE THREAD

**Issue by 0-NiK-0** [alemelis/sd-webui-ar#15]
I changed your style.css to get bigger buttons

```
#txt2img_row_aspect_ratio button,
#img2img_row_aspect_ratio button {
	min-width: 45px !important;
	max-width: 100% !important;
	margin-bottom: 10px !important;
}

#txt2img_row_resolutions button,
#img2img_row_resolutions button {
	min-width: 85px !important;
	max-width: 100% !important;
	margin: 0 0 0.25em 0 !important;
}
```

Before
<img width="635" alt="NiK-01" src="https://user-images.githubusercontent.com/126181396/229845896-ca01f0f8-b0cb-4ed8-93e2-113b79f08f72.png">
<img width="272" alt="Снимок экрана 2023-04-04 180523" src="https://user-images.githubusercontent.com/126181396/229845911-61aa2626-a194-4039-a387-3fd2c9c272cc.png">

My CSS
<img width="634" alt="+NiK-01" src="https://user-images.githubusercontent.com/126181396/229846359-7b66d318-51f9-4c31-84a1-b3d8af83c3f8.png">
<img width="298" alt="+NiK-02" src="https://user-images.githubusercontent.com/126181396/229846372-f209bdce-65c7-4e2d-995b-2db4ca5584df.png">

**Comment by alemelis** [comment]
love it, can you open a PR with this?

**Comment by 0-NiK-0** [comment]
In the new version, my CSS breaks the Calculator.
I don't need a Calculator.
I turned off the Calculator for myself.

```
#txt2img_row_aspect_ratio button,
#img2img_row_aspect_ratio button {
	min-width: 45px !important;
	max-width: 100% !important;
}

#txt2img_row_resolutions button,
#img2img_row_resolutions button {
	min-width: 85px !important;
	max-width: 100% !important;
}

button#arc_show_calculator_button {
display: none;
}
```

<img width="637" alt="1" src="https://user-images.githubusercontent.com/126181396/231810288-946d588a-a6d1-4fd6-b9ff-1f79f88491a3.png">
<img width="298" alt="2" src="https://user-images.githubusercontent.com/126181396/231810298-fc2fc543-bae9-47b2-9b55-948c36cffb5a.png">

**Comment by LEv145** [comment]
How do you like this style option?
![изображение](https://github.com/alemelis/sd-webui-ar/assets/40071054/6c9c8679-3ff6-43d4-9e8f-4694f537f13e)
https://github.com/LEv145/--sd-webui-ar-plus

**Comment by alemelis** [comment]
> How do you like this style option?
> 
> ![изображение](https://github.com/alemelis/sd-webui-ar/assets/40071054/6c9c8679-3ff6-43d4-9e8f-4694f537f13e)
> 
> https://github.com/LEv145/--sd-webui-ar-plus

Love it!
Mind opening a PR with this style?

**Comment by LEv145** [comment]
> > How do you like this style option?
> > ![изображение](https://user-images.githubusercontent.com/40071054/250217341-6c9c8679-3ff6-43d4-9e8f-4694f537f13e.png)
> > https://github.com/LEv145/--sd-webui-ar-plus
> 
> Love it! Mind opening a PR with this style?

Okay, I'll have to add some details to the gradio
