### ISSUE TITLE
GradioDeprecationWarning in webui 1.6

### ISSUE THREAD

**Issue by eunnone** [alemelis/sd-webui-ar#21]
With the update to the webui 1.6 version and gradio, theres some GradioDeprecationWarning

```
C:\Sv\SD_Auto\extensions\sd-webui-ar\scripts\sd-webui-ar.py:433: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  arc_calc_height = gr.Button(value="Calculate Height").style(
C:\Sv\SD_Auto\extensions\sd-webui-ar\scripts\sd-webui-ar.py:433: GradioDeprecationWarning: Use `scale` in place of full_width in the constructor. scale=1 will make the button expand, whereas 0 will not.
  arc_calc_height = gr.Button(value="Calculate Height").style(
C:\Sv\SD_Auto\extensions\sd-webui-ar\scripts\sd-webui-ar.py:441: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  arc_calc_width = gr.Button(value="Calculate Width").style(
C:\Sv\SD_Auto\extensions\sd-webui-ar\scripts\sd-webui-ar.py:441: GradioDeprecationWarning: Use `scale` in place of full_width in the constructor. scale=1 will make the button expand, whereas 0 will not.
 arc_calc_width = gr.Button(value="Calculate Width").style(
```

**Comment by Neytiri7** [comment]
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py:433: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  arc_calc_height = gr.Button(value="Calculate Height").style(
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py:433: GradioDeprecationWarning: Use `scale` in place of full_width in the constructor. scale=1 will make the button expand, whereas 0 will not.
  arc_calc_height = gr.Button(value="Calculate Height").style(
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py:441: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  arc_calc_width = gr.Button(value="Calculate Width").style(
O:\AI\SynologyDrive\stable-diffusion-webui\extensions\sd-webui-ar\scripts\sd-webui-ar.py:441: GradioDeprecationWarning: Use `scale` in place of full_width in the constructor. scale=1 will make the button expand, whereas 0 will not.
  arc_calc_width = gr.Button(value="Calculate Width").style(

**Comment by lewist01** [comment]
Have the error so have removed extension until fixed

**Comment by alemelis** [comment]
@eunnone @Neytiri7 @lewist01 those horrible warnings are gone in the new version
