### ISSUE TITLE
idea: make resolution presets

### ISSUE THREAD

**Issue by gsgoldma** [alemelis/sd-webui-ar#3]
maybe just a button that will quickly set it to 512, 768, 1024, etc..some commonly used resolutions. it can help 'reset' the picture much more quickly than sliding to a precise spot

**Comment by alemelis** [comment]
Very good idea! Should be easy to implement

It could be 3 new buttons for 403, 512 and 768px. These would also set a 1:1 aspect ratio.

**Comment by Woisek** [comment]
> Very good idea! Should be easy to implement
> 
> It could be 3 new buttons for 403, 512 and 768px. These would also set a 1:1 aspect ratio.

Would be cool, but please make them editable and not fixed. Different user have different needs. :)

**Comment by alemelis** [comment]
<img width="659" alt="Screenshot 2023-02-05 at 11 26 32" src="https://user-images.githubusercontent.com/4661737/216922488-fe484735-af16-477f-bd2d-a8606b89a082.png">

this is how the ui looks now at 9c2a7edcebd123b331468498500e705f1d958782

**Comment by Woisek** [comment]
Working good, except for one thing:
Are those resolutions only for 1:1 ratios? I added `543, 768` and `2048, 640` but it makes it square ... :/
Also, a custom label would be cool to have as third parameter. :)

**Comment by alemelis** [comment]
> Working good, except for one thing:
> Are those resolutions only for 1:1 ratios? I added `543, 768` and `2048, 640` but it makes it square ... :/
> Also, a custom label would be cool to have as third parameter. :)

yes, they reset to 1:1
but now that you get me thinking about it, it makes more sense to let the user pick any resolution

**Comment by alemelis** [comment]
<img width="671" alt="Screenshot 2023-02-06 at 14 03 28" src="https://user-images.githubusercontent.com/4661737/216992603-7ca1b3d0-6317-4579-a4b0-68991e8ced45.png">

**Comment by alemelis** [comment]
updated in main

**Comment by Woisek** [comment]
Working now perfect. Thanks! :D
