### ISSUE TITLE
Portrait aspect ratios don't work as expected

### ISSUE THREAD

**Issue by Javalar** [alemelis/sd-webui-ar#7]
Landscape aspect ratios (those over 1.0) adjust the width according to the height by multiplying the height by the aspect ratio. So if the ratio is `3:2` (or `1.5`) and our height is 100px, we get: `width = 100px * 1.5 = 150px`. With a width of 150px and a height of 100px, we indeed get an aspect ratio of 1.5.

But if the aspect ratio is in portrait format (lower than 1.0), the *height* is adjusted according to the *width* using that exact number. So if the ratio is `2:3`  (or `0.667`) and our width is 100px, we get: `height = 100px * 0.667 = 66px`. But that isn't correct! That actually gives us,  once again, an aspect ratio of 1.5! (`100px / 66px = 1.5`)

Changing the line:
```python
            h = self.ar * w
```

...to...

```python
            h = w / self.ar
```

...would fix the problem.

**Comment by alemelis** [comment]
this is very well spotted bug, fixed now!
