### ISSUE TITLE
we are working on a built-in solution

### ISSUE THREAD

**Issue by w-e-w** [alemelis/sd-webui-ar#8]
just a heads up, me and @Gerschel are working on a different approach
a built-in solution using javascript
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7601
if our code gets pulled, this extension may be a largely obsolete

**Comment by alemelis** [comment]
Sounds good to me, go ahead!

I've published this extension only because my built in changes were rejected. As well as another PR before that.
